cmd_/home/virtual/pdma-v1.3-src/pdma-user-intr.o := gcc -Wp,-MD,/home/virtual/pdma-v1.3-src/.pdma-user-intr.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-redhat-linux/4.4.7/include -I/usr/src/kernels/3.10.43-11.el6.centos.alt.x86_64/arch/x86/include -Iarch/x86/include/generated  -Iinclude -I/usr/src/kernels/3.10.43-11.el6.centos.alt.x86_64/arch/x86/include/uapi -Iarch/x86/include/generated/uapi -I/usr/src/kernels/3.10.43-11.el6.centos.alt.x86_64/include/uapi -Iinclude/generated/uapi -include /usr/src/kernels/3.10.43-11.el6.centos.alt.x86_64/include/linux/kconfig.h -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -O2 -m64 -mno-mmx -mno-sse -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -maccumulate-outgoing-args -fstack-protector -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_AVX=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -Wframe-larger-than=2048 -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -pg -fno-inline-functions-called-once -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(pdma_user_intr)"  -D"KBUILD_MODNAME=KBUILD_STR(pdma)" -c -o /home/virtual/pdma-v1.3-src/.tmp_pdma-user-intr.o /home/virtual/pdma-v1.3-src/pdma-user-intr.c

source_/home/virtual/pdma-v1.3-src/pdma-user-intr.o := /home/virtual/pdma-v1.3-src/pdma-user-intr.c

deps_/home/virtual/pdma-v1.3-src/pdma-user-intr.o := \

/home/virtual/pdma-v1.3-src/pdma-user-intr.o: $(deps_/home/virtual/pdma-v1.3-src/pdma-user-intr.o)

$(deps_/home/virtual/pdma-v1.3-src/pdma-user-intr.o):
